

development:
  adapter: postgresql
  encoding: utf8
  database: pairbnb_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pairbnb_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: pairbnb_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST